# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - androidtry
  - mavenDeploy

maven-build:   #this is a JOB
  stage: mavenbuild
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd tutorials/inClass
    - mvn package -B
  artifacts:
    paths:
      - tutorials/inClass/target/*.jar

android-build: #this is another job
  image: javiersantos/android-ci:latest      # this is a directive to DOCKER
  stage: androidtry
  tags:
   - android_tag         #this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    - ./gradlew assemble

# Below job builds, deploys, executes jar as service.
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot_tag
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo


